name: core
version: 0.0.1-SNAPSHOT
description: This is a simple Bukkit Plugin
author: Dihego
main: com.diamond.core.Main
commands: 
   var:
   tag:
   tp:
      aliases: [teletransporte, teleport]
   gm:
      aliases: [gamemode]